# shellcheck shell=bash
# pegada-term bash hook. Generated by `pegada-term init bash`; do not edit.
#
# Everything below runs on shell builtins: no fork per command (bash >= 5).
# bash 3.2 has no sub-second clock, so there each timestamp costs one perl.
# The binary is only called to (re)start the sampler, which is rare and
# rate-limited.

__pegada_term_bin='@BIN@'
__pegada_term_state='@RUNTIME@/state'
__pegada_term_session='@RUNTIME@/sessions/'$$
__pegada_term_history='@STATE@/history.tsv'
__pegada_term_cmd=
__pegada_term_lines=()
__pegada_term_on=1
__pegada_term_pending=0
__pegada_term_busy=0
__pegada_term_armed=0
__pegada_term_osc=0
# Time (ms) and energy (mJ) when the current command started.
__pegada_term_t0=0
__pegada_term_e0=-1
# Last state line: sample time, energy, power, idle power, interval, resolution.
__pegada_term_st=0
__pegada_term_se=0
__pegada_term_sp=0
__pegada_term_si=0
__pegada_term_sn=0
__pegada_term_sr=0
__pegada_term_e=-1
# Sampler restarts: time of the last attempt, current backoff, hint shown.
__pegada_term_kick_t=0
__pegada_term_backoff=5000
__pegada_term_hinted=0
__pegada_term_ses_mj=0
__pegada_term_ses_above=0
__pegada_term_ses_n=0
# Results of the helpers below.
__pegada_term_now=0
__pegada_term_r=
# For prompt frameworks: always set, whatever the style. Exported so prompts
# that run as a separate process (starship) can read it.
export PEGADA_TERM_SEGMENT=

# Sparkline bars, lowest to highest, with a green-to-red gradient per bar.
__pegada_term_bars=('▁' '▂' '▃' '▄' '▅' '▆' '▇' '█')
__pegada_term_bars_ascii=('_' '.' ':' '-' '=' '+' '*' '#')
__pegada_term_bars_color=()
__pegada_term_bars_ascii_color=()
__pegada_term_i=0
for __pegada_term_shade in 71 107 143 179 215 214 208 203; do
  __pegada_term_bars_color[__pegada_term_i]=$'\e[38;5;'${__pegada_term_shade}m${__pegada_term_bars[__pegada_term_i]}
  __pegada_term_bars_ascii_color[__pegada_term_i]=$'\e[38;5;'${__pegada_term_shade}m${__pegada_term_bars_ascii[__pegada_term_i]}
  ((__pegada_term_i++))
done
unset __pegada_term_i __pegada_term_shade

# iTerm2 and WezTerm show user variables in their status bar.
case ${TERM_PROGRAM-}:${LC_TERMINAL-}:${WEZTERM_PANE:+wez} in
  iTerm.app:* | WezTerm:* | *:iTerm2:* | *:wez) __pegada_term_osc=1 ;;
esac

# Epoch milliseconds in __pegada_term_now.
if [[ -n ${EPOCHREALTIME-} ]]; then
  __pegada_term_clock() {
    # The decimal separator follows the locale.
    local t=$EPOCHREALTIME us
    us=${t#*[.,]}
    __pegada_term_now=${t%[.,]*}${us:0:3}
  }
else
  __pegada_term_clock() {
    __pegada_term_now=$(perl -MTime::HiRes=time -e 'printf "%d", time * 1000' 2>/dev/null)
    [[ -n $__pegada_term_now ]] || __pegada_term_now=$(($(date +%s) * 1000))
  }
fi

# The sampler is down: start it, but no more often than the backoff allows.
__pegada_term_kick() {
  local now=$1
  ((now - __pegada_term_kick_t < __pegada_term_backoff)) && return
  if ((__pegada_term_kick_t)); then
    # The previous start produced no samples: slow down, and say so once.
    ((__pegada_term_backoff = __pegada_term_backoff < 150000 ? __pegada_term_backoff * 2 : 300000))
    if ((!__pegada_term_hinted)); then
      __pegada_term_hinted=1
      # shellcheck disable=SC2016
      printf '%s\n' 'pegada-term: sensor unavailable - run `pegada-term doctor`'
    fi
  fi
  __pegada_term_kick_t=$now
  [[ -x $__pegada_term_bin ]] || return
  # Register again: the runtime directory may have been wiped.
  { : >|"$__pegada_term_session"; } 2>/dev/null
  __pegada_term_busy=0
  "$__pegada_term_bin" daemon --start </dev/null >/dev/null 2>&1
}

# One byte per transition: an odd session file length tells the sampler that
# a command is running. $1: the new state.
__pegada_term_mark() {
  { printf 1 >>"$__pegada_term_session"; } 2>/dev/null
  __pegada_term_busy=$1
}

# The state file into the array __pegada_term_lines, in one builtin read.
# (`$(<file)` would fork.)
if ((BASH_VERSINFO[0] >= 4)); then
  __pegada_term_slurp() {
    __pegada_term_lines=()
    { mapfile -t __pegada_term_lines <"$__pegada_term_state"; } 2>/dev/null
  }
else
  __pegada_term_slurp() {
    local line i=0
    __pegada_term_lines=()
    { while IFS= read -r line; do __pegada_term_lines[i++]=$line; done <"$__pegada_term_state"; } 2>/dev/null
  }
fi

# Reads the state file and sets __pegada_term_e to the energy (mJ) at time $1
# (ms): E(t) = E_sample + P_sample * (t - t_sample).
__pegada_term_load() {
  local now=$1 age IFS=' '
  local -a f
  __pegada_term_e=-1
  __pegada_term_slurp
  # seq t_ms energy_mJ power_mW idle_mW interval_ms source res_ms seq
  # Digits and one word, so unquoted splitting cannot glob.
  # shellcheck disable=SC2206
  f=(${__pegada_term_lines[0]-})
  if ((${#f[@]} < 7)); then
    __pegada_term_kick "$now"
    return 1
  fi
  # The trailing seq differs only if the line was read mid-write.
  ((${#f[@]} >= 9)) && [[ ${f[0]} != "${f[8]}" ]] && return 1
  __pegada_term_st=${f[1]} __pegada_term_se=${f[2]} __pegada_term_sp=${f[3]}
  __pegada_term_si=${f[4]} __pegada_term_sn=${f[5]} __pegada_term_sr=${f[7]-0}
  age=$((now - __pegada_term_st))
  if ((__pegada_term_sn <= 0 || age > 4 * __pegada_term_sn + 2000)); then
    __pegada_term_kick "$now"
    return 1
  fi
  __pegada_term_kick_t=0
  __pegada_term_backoff=5000
  ((__pegada_term_sr < __pegada_term_sn)) && __pegada_term_sr=$__pegada_term_sn
  ((age < 0)) && age=0
  # Do not extrapolate further than two intervals past the sample.
  ((age > 2 * __pegada_term_sn)) && age=$((2 * __pegada_term_sn))
  __pegada_term_e=$((__pegada_term_se + __pegada_term_sp * age / 1000))
  return 0
}

# mJ -> "142 J" in __pegada_term_r. Units: mJ / J / kJ / Wh / kWh.
__pegada_term_fmt_energy() {
  local v=$1
  if ((v < 1000)); then
    __pegada_term_r="$v mJ"
  elif ((v < 10000)); then
    __pegada_term_r="$((v / 1000)).$((v % 1000 / 100)) J"
  elif ((v < 1000000)); then
    __pegada_term_r="$((v / 1000)) J"
  elif ((v < 10000000)); then
    __pegada_term_r="$((v / 1000000)).$((v % 1000000 / 100000)) kJ"
  elif ((v < 100000000)); then
    __pegada_term_r="$((v / 1000000)) kJ"
  elif ((v < 3600000000)); then
    __pegada_term_r="$((v / 3600000)).$((v % 3600000 / 360000)) Wh"
  else
    __pegada_term_r="$((v / 3600000000)).$((v % 3600000000 / 360000000)) kWh"
  fi
}

# ms -> "12.4 s" in __pegada_term_r. Units: ms / s / m s / h m.
__pegada_term_fmt_time() {
  local v=$1 s=$(($1 / 1000))
  if ((v < 1000)); then
    __pegada_term_r="$v ms"
  elif ((v < 60000)); then
    __pegada_term_r="$s.$((v % 1000 / 100)) s"
  elif ((v < 3600000)); then
    __pegada_term_r="$((s / 60))m $((s % 60))s"
  else
    __pegada_term_r="$((s / 3600))h $((s % 3600 / 60))m"
  fi
}

# Sparkline of the last $1 ms in __pegada_term_r, from the finest history line
# that covers them, averaged down to at most 16 bars. $2: colour, $3: UTF-8.
__pegada_term_spark() {
  local dur=$1 color=$2 utf8=$3 step=$__pegada_term_sn
  local line IFS=' '
  __pegada_term_r=
  # Lines 2-4 of the state file, as left by __pegada_term_load.
  if ((dur <= 64 * step)); then
    line=${__pegada_term_lines[1]-}
  elif ((dur <= 640 * step)); then
    line=${__pegada_term_lines[2]-} step=$((step * 10))
  else
    line=${__pegada_term_lines[3]-} step=$((step * 100))
  fi
  local -a hist vals
  # Digits and spaces only, so unquoted splitting cannot glob.
  # shellcheck disable=SC2206
  hist=($line)
  local n=$((dur / step + 1))
  ((n > ${#hist[@]})) && n=${#hist[@]}
  ((n < 3)) && return
  local bars=$((n < 16 ? n : 16)) b lo hi v top=0 base=$__pegada_term_si level out=''
  # hist is newest first; bar 0 is the oldest part of the command. A bar is
  # the mean of the first and last sample of its group (no inner loop).
  for ((b = 0; b < bars; b++)); do
    hi=$((n - 1 - b * n / bars)) lo=$((n - (b + 1) * n / bars))
    v=$(((hist[lo] + hist[hi]) / 2))
    vals[b]=$v
    ((v > top)) && top=$v
  done
  # Bars go from the idle baseline to the command's peak, over a range of at
  # least half the idle power, so noise around idle stays flat.
  local range=$((base / 2 > 1000 ? base / 2 : 1000))
  ((top < base + range)) && top=$((base + range))
  # Bars are whole array elements, never slices of a multibyte string, so the
  # locale cannot split a character.
  local -a glyphs
  if ((utf8 && color)); then
    glyphs=("${__pegada_term_bars_color[@]}")
  elif ((utf8)); then
    glyphs=("${__pegada_term_bars[@]}")
  elif ((color)); then
    glyphs=("${__pegada_term_bars_ascii_color[@]}")
  else
    glyphs=("${__pegada_term_bars_ascii[@]}")
  fi
  for v in "${vals[@]}"; do
    level=$(((v - base) * 8 / (top - base)))
    ((level < 0)) && level=0
    ((level > 7)) && level=7
    out+=${glyphs[level]}
  done
  ((color)) && out+=$'\e[0m'
  __pegada_term_r=$out
}

# First word plus subcommand of a command line in __pegada_term_r ("cargo build").
# Never arguments: a second word is kept only for tools known to take subcommands.
__pegada_term_head() {
  local -a w
  local i=0 head sub noglob='' IFS=$' \t\n'
  # Split on blanks without expanding wildcards in the command line.
  [[ $- == *f* ]] || noglob=1
  set -f
  # shellcheck disable=SC2206
  w=($1)
  [[ -n $noglob ]] && set +f
  while ((i < ${#w[@]} - 1)); do
    case ${w[i]} in
      *=* | sudo | time | command | builtin | exec | nice | env) ((i++)) ;;
      *) break ;;
    esac
  done
  [[ ${w[i]-} == -* ]] && ((i > 0)) && ((i--))
  head=${w[i]-}
  head=${head##*/}
  sub=${w[i + 1]-}
  [[ -z $head || $head == *[^A-Za-z0-9._+@-]* ]] && head='?'
  case $head in
    git | cargo | npm | pnpm | yarn | docker | podman | kubectl | go | brew | apt | apt-get | dnf | pip | pip3 | uv | gh | terraform | systemctl | rustup | conda | poetry | bundle | dotnet | mvn | gradle | nix | helm | aws | gcloud | az)
      [[ -n $sub && $sub != -* && $sub != *[^a-z0-9-]* ]] && head+=" $sub"
      ;;
  esac
  __pegada_term_r=$head
}

# Base64 of an ASCII string in __pegada_term_r, for OSC 1337.
__pegada_term_b64() {
  local s=$1 out='' abc='ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/'
  local i n=${#1} a b c
  for ((i = 0; i < n; i += 3)); do
    b=0 c=0
    printf -v a %d "'${s:i:1}"
    ((i + 1 < n)) && printf -v b %d "'${s:i+1:1}"
    ((i + 2 < n)) && printf -v c %d "'${s:i+2:1}"
    out+=${abc:a>>2:1}${abc:((a & 3) << 4) | (b >> 4):1}
    if ((i + 1 < n)); then out+=${abc:((b & 15) << 2) | (c >> 6):1}; else out+='='; fi
    if ((i + 2 < n)); then out+=${abc:c&63:1}; else out+='='; fi
  done
  __pegada_term_r=$out
}

# OSC 1337 SetUserVar for name/value pairs, in one write; wrapped for tmux
# passthrough when needed.
__pegada_term_uservars() {
  local out=''
  while (($# >= 2)); do
    __pegada_term_b64 "$2"
    if [[ -n ${TMUX-} ]]; then
      # shellcheck disable=SC1003
      out+=$'\ePtmux;\e\e]1337;SetUserVar='$1=$__pegada_term_r$'\a\e\\'
    else
      out+=$'\e]1337;SetUserVar='$1=$__pegada_term_r$'\a'
    fi
    shift 2
  done
  printf '%s' "$out"
}

__pegada_term_preexec() {
  ((__pegada_term_on)) || return 0
  __pegada_term_clock
  __pegada_term_t0=$__pegada_term_now
  __pegada_term_cmd=$1
  __pegada_term_pending=1
  __pegada_term_load "$__pegada_term_t0"
  __pegada_term_e0=$__pegada_term_e
  ((__pegada_term_busy)) || __pegada_term_mark 1
  return 0
}

__pegada_term_precmd() {
  local ec=$?
  __pegada_term_armed=0
  ((__pegada_term_busy)) && __pegada_term_mark 0
  # Nothing ran (empty line, ^C at the prompt): print nothing.
  ((__pegada_term_pending)) || return "$ec"
  __pegada_term_pending=0
  __pegada_term_clock
  local now=$__pegada_term_now
  local dur=$((now - __pegada_term_t0)) e0=$__pegada_term_e0
  PEGADA_TERM_SEGMENT=
  __pegada_term_load "$now" || return "$ec"
  ((e0 >= 0 && dur >= 0 && __pegada_term_e >= e0)) || return "$ec"

  local style=${PEGADA_TERM_STYLE:-line} quiet=0 utf8=1 color=1
  ((dur < ${PEGADA_TERM_MIN_MS:-0})) && quiet=1
  [[ $style == off ]] && quiet=1
  [[ -n ${NO_COLOR-} ]] && color=0
  case ${LC_ALL:-${LC_CTYPE:-${LANG-}}} in
    *[Uu][Tt][Ff]-8* | *[Uu][Tt][Ff]8*) ;;
    *) utf8=0 ;;
  esac
  [[ ${PEGADA_TERM_ASCII:-0} != 0 ]] && utf8=0
  local bolt='⚡' dot='·' dim='' rst=''
  ((utf8)) || bolt='*' dot='|'
  ((color)) && dim=$'\e[2m' rst=$'\e[0m'

  if ((dur < 2 * __pegada_term_sr)); then
    # Below the sensor's resolution: no number, so none can look precise.
    ((utf8)) || dot='.'
    PEGADA_TERM_SEGMENT="$bolt $dot"
    if ((!quiet)); then
      printf '%*s\r' $((${COLUMNS:-80} - 1)) ''
      printf '%s\n' "$dim$bolt $dot$rst"
    fi
    return "$ec"
  fi

  local total=$((__pegada_term_e - e0))
  # Above idle: what the machine used beyond its idle baseline for this long.
  local above=$((total - __pegada_term_si * dur / 1000))
  ((above < 0)) && above=0
  ((__pegada_term_ses_mj += total, __pegada_term_ses_above += above, __pegada_term_ses_n++))
  local approx='' e_total e_above e_session
  ((dur < 4 * __pegada_term_sr)) && approx='~'
  __pegada_term_fmt_energy "$total"
  e_total=$approx$__pegada_term_r
  __pegada_term_fmt_energy "$above"
  e_above=$approx$__pegada_term_r
  __pegada_term_fmt_energy "$__pegada_term_ses_mj"
  e_session=$__pegada_term_r
  PEGADA_TERM_SEGMENT="$bolt $e_total"

  if [[ ${PEGADA_TERM_HISTORY:-1} != 0 ]]; then
    __pegada_term_head "$__pegada_term_cmd"
    { printf '%s\t%s\t%s\t%s\t%s\t%s\n' "${now%???}" "$dur" "$total" "$above" "$ec" "$__pegada_term_r" >>"$__pegada_term_history"; } 2>/dev/null
  fi
  if ((__pegada_term_osc)); then
    __pegada_term_uservars pegadaTermLast "$e_total" pegadaTermAbove "$e_above" pegadaTermSession "$e_session"
  fi
  ((quiet)) && return "$ec"

  # If the command's output did not end in a newline, this moves to a fresh
  # line; otherwise the spaces fit on the current one and \r returns to its start.
  printf '%*s\r' $((${COLUMNS:-80} - 1)) ''
  if [[ $style == compact ]]; then
    printf '%s\n' "$dim$bolt$rst $e_total"
    return "$ec"
  fi
  local e_time watts heat='' spark mw=$((total * 1000 / dur))
  __pegada_term_fmt_time "$dur"
  e_time=$__pegada_term_r
  if ((mw < 1000)); then watts="$mw mW"; else watts="$((mw / 1000)).$((mw % 1000 / 100)) W"; fi
  if ((color)); then
    # Green below 100 J above idle, amber below 1 kJ, red from there.
    if ((above < 100000)); then
      heat=$'\e[38;5;71m'
    elif ((above < 1000000)); then
      heat=$'\e[38;5;214m'
    else
      heat=$'\e[38;5;203m'
    fi
  fi
  __pegada_term_spark "$dur" "$color" "$utf8"
  spark=${__pegada_term_r:+ $__pegada_term_r  }
  printf '%s\n' "$dim$bolt $e_total total $dot $rst$heat$e_above$rst$dim above idle $dot $e_time $dot $watts $rst$spark$dim$dot session $e_session$rst"
  return "$ec"
}

# `pegada-term on|off` toggles this shell; everything else goes to the binary,
# with this session's totals for `status`.
pegada-term() {
  # shellcheck disable=SC2034
  case ${1-} in
    on) __pegada_term_on=1 ;;
    off) __pegada_term_on=0 __pegada_term_pending=0 PEGADA_TERM_SEGMENT='' ;;
    *)
      PEGADA_TERM_SESSION_MJ=$__pegada_term_ses_mj \
        PEGADA_TERM_SESSION_ABOVE_MJ=$__pegada_term_ses_above \
        PEGADA_TERM_SESSION_CMDS=$__pegada_term_ses_n \
        "$__pegada_term_bin" "$@"
      ;;
  esac
}

if [[ $- == *i* ]]; then
  # Register this shell: the sampler lives as long as some session file's pid
  # does. Empty (even length) means "at the prompt".
  { : >|"$__pegada_term_session"; } 2>/dev/null

  if [[ -n ${bash_preexec_imported-}${__bp_imported-} ]]; then
    # bash-preexec is loaded: use its hooks.
    preexec_functions+=(__pegada_term_preexec)
    precmd_functions+=(__pegada_term_precmd)
  else
    # No bash-preexec: a DEBUG trap that fires once per command line, armed
    # by the last entry of PROMPT_COMMAND.
    __pegada_term_arm() {
      local ec=$?
      __pegada_term_armed=1
      return "$ec"
    }
    __pegada_term_debug() {
      ((__pegada_term_armed)) || return 0
      # Not for completion functions, nor for our own prompt command.
      [[ -n ${COMP_LINE-} || $BASH_COMMAND == __pegada_term_* ]] && return 0
      __pegada_term_armed=0
      __pegada_term_preexec "$BASH_COMMAND"
    }
    # Keep a DEBUG trap that was already there.
    __pegada_term_prev_debug=
    # shellcheck disable=SC2329
    __pegada_term_get_trap() { __pegada_term_prev_debug=${3-}; }
    eval "__pegada_term_get_trap $(trap -p DEBUG)"
    unset -f __pegada_term_get_trap
    if [[ -n $__pegada_term_prev_debug && $__pegada_term_prev_debug != *__pegada_term_debug* ]]; then
      trap '__pegada_term_debug; eval "$__pegada_term_prev_debug"' DEBUG
    else
      trap '__pegada_term_debug' DEBUG
    fi
    # precmd goes first so it sees the command's exit status; arm goes last.
    if [[ ${BASH_VERSINFO[0]} -ge 5 && "$(declare -p PROMPT_COMMAND 2>/dev/null)" == 'declare -a'* ]]; then
      PROMPT_COMMAND=(__pegada_term_precmd "${PROMPT_COMMAND[@]}" __pegada_term_arm)
    else
      __pegada_term_pc=${PROMPT_COMMAND-}
      # Strip trailing blanks and semicolons so joining cannot produce ";;".
      while [[ $__pegada_term_pc == *[\;[:space:]] ]]; do __pegada_term_pc=${__pegada_term_pc%?}; done
      # shellcheck disable=SC2178
      PROMPT_COMMAND="__pegada_term_precmd${__pegada_term_pc:+; $__pegada_term_pc}; __pegada_term_arm"
      unset __pegada_term_pc
    fi
  fi
fi
