# pegada-term fish hook. Generated by `pegada-term init fish`; do not edit.
#
# Everything below runs on fish builtins: no fork per command. fish has no
# millisecond clock, so a command's energy is $CMD_DURATION times the average
# power between the sampler's state at its start and at its end. The binary is
# only called to (re)start the sampler, which is rare and rate-limited.

set -g __pegada_term_bin '@BIN@'
set -g __pegada_term_state '@RUNTIME@/state'
set -g __pegada_term_sessions '@RUNTIME@/sessions'
set -g __pegada_term_session $__pegada_term_sessions/$fish_pid
set -g __pegada_term_history '@STATE@/history.tsv'
set -g __pegada_term_on 1
set -g __pegada_term_pending 0
set -g __pegada_term_busy 0
set -g __pegada_term_cmd ''
# State line (seq t_ms energy_mJ power_mW idle_mW interval_ms source res_ms seq)
# as read now, and as it was when the current command started.
set -g __pegada_term_s
set -g __pegada_term_s0
set -g __pegada_term_last_seq -1
# Sampler restarts: epoch seconds of the last attempt, backoff in seconds,
# prompts left to skip before looking again, hint shown.
set -g __pegada_term_kick_t 0
set -g __pegada_term_backoff 5
set -g __pegada_term_skip 0
set -g __pegada_term_hinted 0
set -g __pegada_term_ses_mj 0
set -g __pegada_term_ses_above 0
set -g __pegada_term_ses_n 0
set -gx PEGADA_TERM_SEGMENT ''

# iTerm2 and WezTerm show user variables in their status bar.
set -g __pegada_term_osc 0
if test "$TERM_PROGRAM" = iTerm.app -o "$TERM_PROGRAM" = WezTerm -o "$LC_TERMINAL" = iTerm2 -o -n "$WEZTERM_PANE"
    set -g __pegada_term_osc 1
end

# Line 1 of the state file into the list __pegada_term_s.
function __pegada_term_read
    set -g __pegada_term_s
    test -r $__pegada_term_state; or return 1
    read -l line <$__pegada_term_state; or return 1
    set -g __pegada_term_s (string split ' ' -- $line)
    test (count $__pegada_term_s) -ge 7; or return 1
    # The trailing seq differs only if the line was read mid-write.
    if set -q __pegada_term_s[9]; and test "$__pegada_term_s[1]" != "$__pegada_term_s[9]"
        set -g __pegada_term_s
        return 1
    end
    set -q __pegada_term_s[8]; or set -g __pegada_term_s[8] $__pegada_term_s[6]
    test $__pegada_term_s[8] -ge $__pegada_term_s[6]; or set -g __pegada_term_s[8] $__pegada_term_s[6]
    return 0
end

# The session file registers this shell. One byte is appended per transition:
# an odd length tells the sampler that a command is running.
function __pegada_term_mark -a busy
    test -d $__pegada_term_sessions; or return
    if test "$busy" = reset
        echo -n >$__pegada_term_session
        set -g __pegada_term_busy 0
    else if test "$busy" != "$__pegada_term_busy"
        echo -n 1 >>$__pegada_term_session
        set -g __pegada_term_busy $busy
    end
end

# The sampler looks down. fish cannot tell the time without forking, so this
# path, and only this path, calls `date`; repeated failures skip more and more
# prompts before looking again.
function __pegada_term_stale
    if test $__pegada_term_skip -gt 0
        set -g __pegada_term_skip (math $__pegada_term_skip - 1)
        return 0
    end
    set -l now (date +%s)
    if test (count $__pegada_term_s) -ge 7
        # Still fresh: the commands were just faster than the sampler.
        set -l age (math -s0 "$now - $__pegada_term_s[2] / 1000")
        test $age -le (math -s0 "(4 * $__pegada_term_s[6] + 2000) / 1000 + 1"); and return 1
    end
    test (math "$now - $__pegada_term_kick_t") -lt $__pegada_term_backoff; and return 0
    if test $__pegada_term_kick_t -gt 0
        # The previous start produced no samples: slow down, and say so once.
        test $__pegada_term_backoff -lt 300; and set -g __pegada_term_backoff (math "$__pegada_term_backoff * 2")
        set -g __pegada_term_skip (math -s0 "$__pegada_term_backoff / 5")
        if test $__pegada_term_hinted = 0
            set -g __pegada_term_hinted 1
            echo 'pegada-term: sensor unavailable - run `pegada-term doctor`'
        end
    end
    set -g __pegada_term_kick_t $now
    test -x $__pegada_term_bin; or return 0
    __pegada_term_mark reset
    $__pegada_term_bin daemon --start </dev/null >/dev/null 2>&1
    return 0
end

# $v / $unit with one decimal, truncated ("12.4"): integer math, like the other shells.
function __pegada_term_tenths -a v unit
    echo (math -s0 "$v / $unit").(math -s0 "($v % $unit) * 10 / $unit")
end

# mJ -> "142 J". Units: mJ / J / kJ / Wh / kWh.
function __pegada_term_fmt_energy -a v
    if test $v -lt 1000
        echo "$v mJ"
    else if test $v -lt 10000
        echo (__pegada_term_tenths $v 1000)" J"
    else if test $v -lt 1000000
        echo (math -s0 "$v / 1000")" J"
    else if test $v -lt 10000000
        echo (__pegada_term_tenths $v 1000000)" kJ"
    else if test $v -lt 100000000
        echo (math -s0 "$v / 1000000")" kJ"
    else if test $v -lt 3600000000
        echo (__pegada_term_tenths $v 3600000)" Wh"
    else
        echo (__pegada_term_tenths $v 3600000000)" kWh"
    end
end

# ms -> "12.4 s". Units: ms / s / m s / h m.
function __pegada_term_fmt_time -a v
    set -l s (math -s0 "$v / 1000")
    if test $v -lt 1000
        echo "$v ms"
    else if test $v -lt 60000
        echo (__pegada_term_tenths $v 1000)" s"
    else if test $v -lt 3600000
        echo (math -s0 "$s / 60")"m "(math "$s % 60")"s"
    else
        echo (math -s0 "$s / 3600")"h "(math -s0 "$s % 3600 / 60")"m"
    end
end

# Sparkline of the last $dur ms, from the finest history line that covers
# them, averaged down to at most 16 bars.
function __pegada_term_spark -a dur color utf8
    set -l step $__pegada_term_s[6]
    set -l base $__pegada_term_s[5]
    set -l lines
    test -r $__pegada_term_state; or return
    while read -l l
        set -a lines "$l"
    end <$__pegada_term_state
    set -l pick 2
    if test $dur -gt (math "640 * $step")
        set pick 4
        set step (math "$step * 100")
    else if test $dur -gt (math "64 * $step")
        set pick 3
        set step (math "$step * 10")
    end
    set -q lines[$pick]; or return
    set -l hist (string split -n ' ' -- $lines[$pick])
    set -l n (math -s0 "$dur / $step + 1")
    test $n -gt (count $hist); and set n (count $hist)
    test $n -lt 3; and return
    set -l bars $n
    test $bars -gt 16; and set bars 16
    set -l vals
    set -l top 0
    set -l b 0
    # hist is newest first; bar 0 is the oldest part of the command.
    while test $b -lt $bars
        set -l hi (math -s0 "$n - floor($b * $n / $bars)")
        set -l lo (math -s0 "$n - floor(($b + 1) * $n / $bars) + 1")
        set -l v (math -s0 "("(string join + $hist[$lo..$hi])") / ($hi - $lo + 1)")
        set -a vals $v
        test $v -gt $top; and set top $v
        set b (math $b + 1)
    end
    # Bars go from the idle baseline to the command's peak, over a range of at
    # least half the idle power, so noise around idle stays flat.
    set -l range (math -s0 "$base / 2")
    test $range -lt 1000; and set range 1000
    test $top -lt (math "$base + $range"); and set top (math "$base + $range")
    set -l out ''
    for v in $vals
        set -l level (math -s0 "($v - $base) * 8 / ($top - $base)")
        # -le, not -lt: older fish prints a small negative result as "-0".
        test $level -le 0; and set level 0
        test $level -gt 7; and set level 7
        set -l ch
        # `switch`, not string slicing: safe whatever the locale does to multibyte characters.
        if test $utf8 = 1
            switch $level
                case 0
                    set ch '▁'
                case 1
                    set ch '▂'
                case 2
                    set ch '▃'
                case 3
                    set ch '▄'
                case 4
                    set ch '▅'
                case 5
                    set ch '▆'
                case 6
                    set ch '▇'
                case '*'
                    set ch '█'
            end
        else
            switch $level
                case 0
                    set ch _
                case 1
                    set ch .
                case 2
                    set ch :
                case 3
                    set ch -
                case 4
                    set ch =
                case 5
                    set ch +
                case 6
                    set ch '*'
                case '*'
                    set ch '#'
            end
        end
        if test $color = 1
            set -l shades 71 107 143 179 215 214 208 203
            set ch \e'[38;5;'$shades[(math $level + 1)]m$ch
        end
        set out $out$ch
    end
    test $color = 1; and set out $out\e'[0m'
    echo -n $out
end

# First word plus subcommand of a command line ("cargo build"). Never
# arguments: a second word is kept only for tools known to take subcommands.
function __pegada_term_head -a line
    set -l w (string split -n ' ' -- (string replace -ra '\s+' ' ' -- $line))
    set -l i 1
    while test $i -lt (count $w)
        if string match -q -- '*=*' $w[$i]; or contains -- $w[$i] sudo time command builtin exec nice env
            set i (math $i + 1)
        else
            break
        end
    end
    if string match -q -- '-*' "$w[$i]"; and test $i -gt 1
        set i (math $i - 1)
    end
    set -l head (string replace -r '.*/' '' -- "$w[$i]")
    set -l sub $w[(math $i + 1)]
    if test -z "$head"; or string match -qr '[^A-Za-z0-9._+@-]' -- $head
        set head '?'
    end
    if contains -- $head git cargo npm pnpm yarn docker podman kubectl go brew apt apt-get dnf pip pip3 uv gh terraform systemctl rustup conda poetry bundle dotnet mvn gradle nix helm aws gcloud az
        if test -n "$sub"; and string match -qr '^[a-z0-9][a-z0-9-]*$' -- $sub
            set head "$head $sub"
        end
    end
    echo $head
end

# Base64 of an ASCII string, for OSC 1337.
function __pegada_term_b64 -a s
    set -l abc ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/
    set -l codes
    for ch in (string split '' -- $s)
        set -a codes (printf '%d' "'$ch")
    end
    set -l n (count $codes)
    set -l i 1
    set -l out ''
    while test $i -le $n
        set -l a $codes[$i]
        set -l b 0
        set -l c 0
        set -q codes[(math $i + 1)]; and set b $codes[(math $i + 1)]
        set -q codes[(math $i + 2)]; and set c $codes[(math $i + 2)]
        set out $out(string sub -s (math -s0 "floor($a / 4) + 1") -l 1 $abc)
        set out $out(string sub -s (math -s0 "($a % 4) * 16 + floor($b / 16) + 1") -l 1 $abc)
        if test (math $i + 1) -le $n
            set out $out(string sub -s (math -s0 "($b % 16) * 4 + floor($c / 64) + 1") -l 1 $abc)
        else
            set out $out=
        end
        if test (math $i + 2) -le $n
            set out $out(string sub -s (math "$c % 64 + 1") -l 1 $abc)
        else
            set out $out=
        end
        set i (math $i + 3)
    end
    echo -n $out
end

# OSC 1337 SetUserVar, wrapped for tmux passthrough when needed.
function __pegada_term_uservar -a name value
    set -l b64 (__pegada_term_b64 $value)
    if set -q TMUX
        printf '\ePtmux;\e\e]1337;SetUserVar=%s=%s\a\e\\' $name $b64
    else
        printf '\e]1337;SetUserVar=%s=%s\a' $name $b64
    end
end

function __pegada_term_preexec --on-event fish_preexec
    test $__pegada_term_on = 1; or return
    set -g __pegada_term_pending 1
    set -g __pegada_term_cmd $argv[1]
    set -g __pegada_term_s0
    __pegada_term_read; and set -g __pegada_term_s0 $__pegada_term_s
    __pegada_term_mark 1
end

function __pegada_term_postexec --on-event fish_postexec
    set -l ec $status
    set -l dur $CMD_DURATION
    __pegada_term_mark 0
    test $__pegada_term_pending = 1; or return
    set -g __pegada_term_pending 0
    set -gx PEGADA_TERM_SEGMENT ''
    set -l s0 $__pegada_term_s0
    set -l seq_before $__pegada_term_last_seq
    __pegada_term_read
    set -l s $__pegada_term_s
    set -g __pegada_term_last_seq "$s[1]"
    # No new sample since this command started, nor since the previous one
    # ended: the sampler may be gone.
    if test (count $s) -lt 7; or test "$s[1]" = "$s0[1]" -a "$s[1]" = "$seq_before"
        __pegada_term_stale; and return
    else
        set -g __pegada_term_kick_t 0
        set -g __pegada_term_backoff 5
        set -g __pegada_term_skip 0
    end
    test (count $s0) -ge 7; or return
    test -n "$dur"; or return

    set -l style line
    set -q PEGADA_TERM_STYLE; and set style $PEGADA_TERM_STYLE
    set -l quiet 0
    set -l utf8 1
    set -l color 1
    set -q PEGADA_TERM_MIN_MS; and test $dur -lt "$PEGADA_TERM_MIN_MS"; and set quiet 1
    test $style = off; and set quiet 1
    set -q NO_COLOR; and test -n "$NO_COLOR"; and set color 0
    set -l locale "$LC_ALL"
    test -z "$locale"; and set locale "$LC_CTYPE"
    test -z "$locale"; and set locale "$LANG"
    string match -qir 'utf-?8' -- $locale; or set utf8 0
    set -q PEGADA_TERM_ASCII; and test "$PEGADA_TERM_ASCII" != 0; and set utf8 0
    set -l bolt '⚡'
    set -l dot '·'
    set -l dim ''
    set -l rst ''
    if test $utf8 = 0
        set bolt '*'
        set dot '|'
    end
    if test $color = 1
        set dim \e'[2m'
        set rst \e'[0m'
    end
    # Spaces, then \r: moves to a fresh line only if the output did not end in a newline.
    set -l cols (math "$COLUMNS - 1")
    test $cols -lt 1; and set cols 1
    set -l pad (string repeat -n $cols ' ')\r

    if test $dur -lt (math "2 * $s[8]")
        # Below the sensor's resolution: no number, so none can look precise.
        test $utf8 = 0; and set dot .
        set -gx PEGADA_TERM_SEGMENT "$bolt $dot"
        test $quiet = 1; or echo $pad$dim$bolt $dot$rst
        return
    end

    # Average power between the sample before the command and the latest one.
    set -l avg $s[4]
    if test $s[2] -gt $s0[2]
        set avg (math -s0 "($s[3] - $s0[3]) * 1000 / ($s[2] - $s0[2])")
    end
    set -l total (math -s0 "$avg * $dur / 1000")
    # Above idle: what the machine used beyond its idle baseline for this long.
    set -l above (math -s0 "$total - $s[5] * $dur / 1000")
    test $above -lt 0; and set above 0
    set -g __pegada_term_ses_mj (math "$__pegada_term_ses_mj + $total")
    set -g __pegada_term_ses_above (math "$__pegada_term_ses_above + $above")
    set -g __pegada_term_ses_n (math "$__pegada_term_ses_n + 1")
    set -l approx ''
    test $dur -lt (math "4 * $s[8]"); and set approx '~'
    set -l e_total $approx(__pegada_term_fmt_energy $total)
    set -l e_above $approx(__pegada_term_fmt_energy $above)
    set -l e_session (__pegada_term_fmt_energy $__pegada_term_ses_mj)
    set -gx PEGADA_TERM_SEGMENT "$bolt $e_total"

    if test "$PEGADA_TERM_HISTORY" != 0; and test -d (string replace -r '/[^/]*$' '' -- $__pegada_term_history)
        set -l now (math -s0 "$s[2] / 1000")
        printf '%s\t%s\t%s\t%s\t%s\t%s\n' $now $dur $total $above $ec (__pegada_term_head $__pegada_term_cmd) >>$__pegada_term_history
    end
    if test $__pegada_term_osc = 1
        __pegada_term_uservar pegadaTermLast $e_total
        __pegada_term_uservar pegadaTermAbove $e_above
        __pegada_term_uservar pegadaTermSession $e_session
    end
    test $quiet = 1; and return

    if test $style = compact
        echo $pad$dim$bolt$rst $e_total
        return
    end
    set -l heat ''
    if test $color = 1
        # Green below 100 J above idle, amber below 1 kJ, red from there.
        if test $above -lt 100000
            set heat \e'[38;5;71m'
        else if test $above -lt 1000000
            set heat \e'[38;5;214m'
        else
            set heat \e'[38;5;203m'
        end
    end
    set -l watts "$avg mW"
    test $avg -ge 1000; and set watts (__pegada_term_tenths $avg 1000)" W"
    set -l spark (__pegada_term_spark $dur $color $utf8)
    test -n "$spark"; and set spark " $spark  "
    echo "$pad$dim$bolt $e_total total $dot $rst$heat$e_above$rst$dim above idle $dot "(__pegada_term_fmt_time $dur)" $dot $watts $rst$spark$dim$dot session $e_session$rst"
end

# `pegada-term on|off` toggles this shell; everything else goes to the binary,
# with this session's totals for `status`.
function pegada-term
    switch "$argv[1]"
        case on
            set -g __pegada_term_on 1
        case off
            set -g __pegada_term_on 0
            set -g __pegada_term_pending 0
            set -gx PEGADA_TERM_SEGMENT ''
        case '*'
            set -lx PEGADA_TERM_SESSION_MJ $__pegada_term_ses_mj
            set -lx PEGADA_TERM_SESSION_ABOVE_MJ $__pegada_term_ses_above
            set -lx PEGADA_TERM_SESSION_CMDS $__pegada_term_ses_n
            $__pegada_term_bin $argv
    end
end

# Register this shell: the sampler lives as long as some session file's pid does.
status is-interactive; and __pegada_term_mark reset
