# pegada-term zsh hook. Generated by `pegada-term init zsh`; do not edit.
#
# Everything below runs on shell builtins: no fork per command. The binary is
# only called to (re)start the sampler, which is rare and rate-limited.
#
# State line: seq t_ms energy_mJ power_mW idle_mW interval_ms source res_ms seq

zmodload zsh/datetime 2>/dev/null
autoload -Uz add-zsh-hook

typeset -g __pegada_term_bin='@BIN@'
typeset -g __pegada_term_state='@RUNTIME@/state'
typeset -g __pegada_term_session='@RUNTIME@/sessions/'$$
typeset -g __pegada_term_history='@STATE@/history.tsv'
typeset -g __pegada_term_cmd=
typeset -ga __pegada_term_lines
typeset -gi __pegada_term_on=1 __pegada_term_pending=0 __pegada_term_osc=0
# Time (ms) and energy (mJ) when the current command started.
typeset -gi __pegada_term_t0=0 __pegada_term_e0=-1
# Last state line: sample time, energy, power, idle power, interval, resolution.
typeset -gi __pegada_term_st=0 __pegada_term_se=0 __pegada_term_sp=0
typeset -gi __pegada_term_si=0 __pegada_term_sn=0 __pegada_term_sr=0
typeset -gi __pegada_term_e=-1
# Sampler restarts: time of the last attempt, current backoff, hint shown.
typeset -gi __pegada_term_kick_t=0 __pegada_term_backoff=5000 __pegada_term_hinted=0
typeset -gi __pegada_term_ses_mj=0 __pegada_term_ses_above=0 __pegada_term_ses_n=0
# For prompt frameworks: always set, whatever the style. Exported so prompts
# that run as a separate process (starship) can read it.
typeset -gx PEGADA_TERM_SEGMENT=

# Sparkline bars, lowest to highest, with a green-to-red gradient per bar.
typeset -ga __pegada_term_bars __pegada_term_bars_ascii __pegada_term_bars_color __pegada_term_bars_ascii_color
__pegada_term_bars=('▁' '▂' '▃' '▄' '▅' '▆' '▇' '█')
__pegada_term_bars_ascii=('_' '.' ':' '-' '=' '+' '*' '#')
() {
  local -a shades=(71 107 143 179 215 214 208 203)
  local -i i
  for (( i = 1; i <= 8; i++ )); do
    __pegada_term_bars_color[i]=$'\e[38;5;'$shades[i]m$__pegada_term_bars[i]
    __pegada_term_bars_ascii_color[i]=$'\e[38;5;'$shades[i]m$__pegada_term_bars_ascii[i]
  done
}

# iTerm2 and WezTerm show user variables in their status bar.
if [[ ${TERM_PROGRAM-} == (iTerm.app|WezTerm) || ${LC_TERMINAL-} == iTerm2 || -n ${WEZTERM_PANE-} ]]; then
  __pegada_term_osc=1
fi

# With zsh/system the three files stay open (close-on-exec, so the commands
# you run do not inherit them) and every access is one or two system calls
# instead of open + read/write + close. Without it, the same by path.
typeset -gi __pegada_term_fast=0 __pegada_term_busy=0
typeset -gi __pegada_term_fd_state=-1 __pegada_term_fd_session=-1 __pegada_term_fd_history=-1
if [[ -z ${PEGADA_TERM_NO_FD-} ]] && zmodload zsh/system 2>/dev/null && (( $+builtins[sysopen] )); then
  __pegada_term_fast=1
fi

# Closes a descriptor held in the variable named $1.
__pegada_term_close() {
  local -i fd=${(P)1}
  (( fd >= 0 )) && exec {fd}>&-
  : ${(P)1::=-1}
}

# The sampler is down: start it, but no more often than the backoff allows.
__pegada_term_kick() {
  local -i now=$1
  (( now - __pegada_term_kick_t < __pegada_term_backoff )) && return
  if (( __pegada_term_kick_t )); then
    # The previous start produced no samples: slow down, and say so once.
    (( __pegada_term_backoff = __pegada_term_backoff < 150000 ? __pegada_term_backoff * 2 : 300000 ))
    if (( ! __pegada_term_hinted )); then
      __pegada_term_hinted=1
      print -r -- 'pegada-term: sensor unavailable - run `pegada-term doctor`'
    fi
  fi
  __pegada_term_kick_t=$now
  [[ -x $__pegada_term_bin ]] || return
  # Register again: the runtime directory may have been wiped.
  __pegada_term_close __pegada_term_fd_session
  { : >| $__pegada_term_session } 2>/dev/null
  __pegada_term_busy=0
  $__pegada_term_bin daemon --start </dev/null >/dev/null 2>&1
}

# One byte per transition: an odd session file length tells the sampler that
# a command is running.
__pegada_term_mark() {
  if (( __pegada_term_fast )); then
    if (( __pegada_term_fd_session < 0 )); then
      sysopen -a -o cloexec,creat -u __pegada_term_fd_session $__pegada_term_session 2>/dev/null ||
        { __pegada_term_fd_session=-1; return }
    fi
    syswrite -o $__pegada_term_fd_session 1 2>/dev/null
  else
    { print -n 1 >> $__pegada_term_session } 2>/dev/null
  fi
}

# The whole state file into __pegada_term_lines. No fork either way: zsh
# reads `$(<file)` itself.
__pegada_term_slurp() {
  local buf=
  if (( __pegada_term_fast )); then
    if (( __pegada_term_fd_state < 0 )); then
      sysopen -r -o cloexec -u __pegada_term_fd_state $__pegada_term_state 2>/dev/null ||
        { __pegada_term_fd_state=-1; __pegada_term_lines=(); return 1 }
    fi
    # The sampler rewrites the file in place, so the descriptor stays valid.
    sysseek -u $__pegada_term_fd_state 0 && sysread -i $__pegada_term_fd_state -s 8192 buf
    __pegada_term_lines=("${(@f)buf}")
  else
    __pegada_term_lines=()
    { __pegada_term_lines=("${(@f)$(<$__pegada_term_state)}") } 2>/dev/null
  fi
}

# Reads the state file and sets __pegada_term_e to the energy (mJ) at time $1
# (ms): E(t) = E_sample + P_sample * (t - t_sample).
__pegada_term_load() {
  local -i now=$1 age try
  local -a f
  __pegada_term_e=-1
  for try in 1 2; do
    __pegada_term_slurp
    # seq t_ms energy_mJ power_mW idle_mW interval_ms source res_ms seq
    f=(${=__pegada_term_lines[1]})
    if (( $#f >= 7 )); then
      # The trailing seq differs only if the line was read mid-write.
      (( $#f >= 9 )) && [[ $f[1] != $f[9] ]] && return 1
      age=$(( now - f[2] ))
      (( f[6] > 0 && age <= 4 * f[6] + 2000 )) && break
    fi
    # Missing or stale. An open descriptor may point at a file that has been
    # replaced: reopen and look once more before concluding the sampler is down.
    if (( try == 2 || __pegada_term_fd_state < 0 )); then
      __pegada_term_kick $now
      return 1
    fi
    __pegada_term_close __pegada_term_fd_state
  done
  __pegada_term_st=$f[2] __pegada_term_se=$f[3] __pegada_term_sp=$f[4]
  __pegada_term_si=$f[5] __pegada_term_sn=$f[6] __pegada_term_sr=${f[8]:-0}
  __pegada_term_kick_t=0 __pegada_term_backoff=5000
  (( __pegada_term_sr < __pegada_term_sn )) && __pegada_term_sr=$__pegada_term_sn
  (( age < 0 )) && age=0
  # Do not extrapolate further than two intervals past the sample.
  (( age > 2 * __pegada_term_sn )) && age=$(( 2 * __pegada_term_sn ))
  __pegada_term_e=$(( __pegada_term_se + __pegada_term_sp * age / 1000 ))
  return 0
}

# Appends a line to history.tsv.
__pegada_term_log() {
  if (( __pegada_term_fast )); then
    # Reopen if the file was deleted or rotated.
    [[ -e $__pegada_term_history ]] || __pegada_term_close __pegada_term_fd_history
    if (( __pegada_term_fd_history < 0 )); then
      sysopen -a -o cloexec,creat -u __pegada_term_fd_history $__pegada_term_history 2>/dev/null ||
        { __pegada_term_fd_history=-1; return }
    fi
    syswrite -o $__pegada_term_fd_history $1$'\n' 2>/dev/null
  else
    { print -r -- $1 >> $__pegada_term_history } 2>/dev/null
  fi
}

# mJ -> "142 J" in REPLY. Units: mJ / J / kJ / Wh / kWh.
__pegada_term_fmt_energy() {
  local -i v=$1
  if (( v < 1000 )); then REPLY="$v mJ"
  elif (( v < 10000 )); then REPLY="$(( v / 1000 )).$(( v % 1000 / 100 )) J"
  elif (( v < 1000000 )); then REPLY="$(( v / 1000 )) J"
  elif (( v < 10000000 )); then REPLY="$(( v / 1000000 )).$(( v % 1000000 / 100000 )) kJ"
  elif (( v < 100000000 )); then REPLY="$(( v / 1000000 )) kJ"
  elif (( v < 3600000000 )); then REPLY="$(( v / 3600000 )).$(( v % 3600000 / 360000 )) Wh"
  else REPLY="$(( v / 3600000000 )).$(( v % 3600000000 / 360000000 )) kWh"
  fi
}

# ms -> "12.4 s" in REPLY. Units: ms / s / m s / h m.
__pegada_term_fmt_time() {
  local -i v=$1 s=$(( $1 / 1000 ))
  if (( v < 1000 )); then REPLY="$v ms"
  elif (( v < 60000 )); then REPLY="$s.$(( v % 1000 / 100 )) s"
  elif (( v < 3600000 )); then REPLY="$(( s / 60 ))m $(( s % 60 ))s"
  else REPLY="$(( s / 3600 ))h $(( s % 3600 / 60 ))m"
  fi
}

# Sparkline of the last $1 ms in REPLY, from the finest history line that
# covers them, averaged down to at most 16 bars. $2: colour, $3: UTF-8.
__pegada_term_spark() {
  local -i dur=$1 color=$2 utf8=$3 step=$__pegada_term_sn
  local line
  REPLY=
  (( step > 0 )) || return
  # Lines 2-4 of the state file, as left by __pegada_term_load.
  if (( dur <= 64 * step )); then line=$__pegada_term_lines[2]
  elif (( dur <= 640 * step )); then line=$__pegada_term_lines[3] step=$(( step * 10 ))
  else line=$__pegada_term_lines[4] step=$(( step * 100 ))
  fi
  local -a hist vals
  hist=(${=line})
  local -i n=$(( dur / step + 1 ))
  (( n > $#hist )) && n=$#hist
  (( n < 3 )) && return
  local -i bars=$(( n < 16 ? n : 16 )) b lo hi v top=0 base=$__pegada_term_si level
  # hist is newest first; bar 0 is the oldest part of the command. A bar is
  # the mean of the first and last sample of its group (no inner loop).
  for (( b = 0; b < bars; b++ )); do
    hi=$(( n - b * n / bars )) lo=$(( n - (b + 1) * n / bars + 1 ))
    v=$(( (hist[lo] + hist[hi]) / 2 ))
    vals+=($v)
    (( v > top )) && top=$v
  done
  # Bars go from the idle baseline to the command's peak, over a range of at
  # least half the idle power, so noise around idle stays flat.
  local -i range=$(( base / 2 > 1000 ? base / 2 : 1000 ))
  (( top < base + range )) && top=$(( base + range ))
  # Bars are whole array elements, never slices of a multibyte string, so the
  # locale cannot split a character.
  local -a glyphs
  if (( utf8 && color )); then glyphs=($__pegada_term_bars_color)
  elif (( utf8 )); then glyphs=($__pegada_term_bars)
  elif (( color )); then glyphs=($__pegada_term_bars_ascii_color)
  else glyphs=($__pegada_term_bars_ascii)
  fi
  for v in $vals; do
    level=$(( (v - base) * 8 / (top - base) + 1 ))
    (( level < 1 )) && level=1
    (( level > 8 )) && level=8
    REPLY+=$glyphs[level]
  done
  (( color )) && REPLY+=$'\e[0m'
}

# First word plus subcommand of a command line in REPLY ("cargo build").
# Never arguments: a second word is kept only for tools known to take subcommands.
__pegada_term_head() {
  local -a w
  w=(${=1})
  local -i i=1
  while (( i < $#w )) && [[ $w[i] == *=* || $w[i] == (sudo|time|command|builtin|noglob|nocorrect|exec|nice|env) ]]; do
    (( i++ ))
  done
  [[ $w[i] == -* ]] && (( i > 1 )) && (( i-- ))
  local head=${w[i]:t} sub=$w[i+1]
  [[ -z $head || $head == *[^A-Za-z0-9._+@-]* || $head == *=* ]] && head='?'
  case $head in
    git|cargo|npm|pnpm|yarn|docker|podman|kubectl|go|brew|apt|apt-get|dnf|pip|pip3|uv|gh|terraform|systemctl|rustup|conda|poetry|bundle|dotnet|mvn|gradle|nix|helm|aws|gcloud|az)
      [[ -n $sub && $sub != -* && $sub != *[^a-z0-9-]* ]] && head+=" $sub" ;;
  esac
  REPLY=$head
}

# Base64 of an ASCII string in REPLY, for OSC 1337.
__pegada_term_b64() {
  local s=$1 ch abc='ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/'
  local -i i n=$#1 a b c k
  REPLY=
  for (( i = 1; i <= n; i += 3 )); do
    ch=$s[i]; a=$(( #ch )) b=0 c=0
    (( i + 1 <= n )) && { ch=$s[i+1]; b=$(( #ch )) }
    (( i + 2 <= n )) && { ch=$s[i+2]; c=$(( #ch )) }
    k=$(( (a >> 2) + 1 )); REPLY+=$abc[k]
    k=$(( (((a & 3) << 4) | (b >> 4)) + 1 )); REPLY+=$abc[k]
    k=$(( (((b & 15) << 2) | (c >> 6)) + 1 ))
    if (( i + 1 <= n )); then REPLY+=$abc[k]; else REPLY+='='; fi
    k=$(( (c & 63) + 1 ))
    if (( i + 2 <= n )); then REPLY+=$abc[k]; else REPLY+='='; fi
  done
}

# OSC 1337 SetUserVar for name/value pairs, in one write; wrapped for tmux
# passthrough when needed.
__pegada_term_uservars() {
  local out= name value
  for name value in "$@"; do
    __pegada_term_b64 $value
    if [[ -n ${TMUX-} ]]; then
      out+=$'\ePtmux;\e\e]1337;SetUserVar='$name=$REPLY$'\a\e\\'
    else
      out+=$'\e]1337;SetUserVar='$name=$REPLY$'\a'
    fi
  done
  print -rn -- $out
}

__pegada_term_preexec() {
  emulate -L zsh
  (( __pegada_term_on )) || return 0
  local t=$EPOCHREALTIME
  __pegada_term_t0=${t%.*}${${t#*.}[1,3]}
  __pegada_term_cmd=$1
  __pegada_term_pending=1
  __pegada_term_load $__pegada_term_t0
  __pegada_term_e0=$__pegada_term_e
  (( __pegada_term_busy )) || { __pegada_term_mark; __pegada_term_busy=1 }
  return 0
}

__pegada_term_precmd() {
  local -i ec=$?
  emulate -L zsh
  (( __pegada_term_busy )) && { __pegada_term_mark; __pegada_term_busy=0 }
  # Nothing ran (empty line, ^C at the prompt): print nothing.
  (( __pegada_term_pending )) || return $ec
  __pegada_term_pending=0
  local t=$EPOCHREALTIME
  local -i now=${t%.*}${${t#*.}[1,3]}
  local -i dur=$(( now - __pegada_term_t0 )) e0=$__pegada_term_e0
  PEGADA_TERM_SEGMENT=
  __pegada_term_load $now || return $ec
  (( e0 >= 0 && dur >= 0 && __pegada_term_e >= e0 )) || return $ec

  local style=${PEGADA_TERM_STYLE:-line}
  local -i quiet=0 utf8=1 color=1
  (( dur < ${PEGADA_TERM_MIN_MS:-0} )) && quiet=1
  [[ $style == off ]] && quiet=1
  [[ -n ${NO_COLOR-} ]] && color=0
  [[ ${PEGADA_TERM_ASCII:-0} != 0 || ${LC_ALL:-${LC_CTYPE:-${LANG-}}} != *[Uu][Tt][Ff](-|)8* ]] && utf8=0
  local bolt='⚡' dot='·' dim= rst=
  (( utf8 )) || bolt='*' dot='|'
  (( color )) && dim=$'\e[2m' rst=$'\e[0m'

  if (( dur < 2 * __pegada_term_sr )); then
    # Below the sensor's resolution: no number, so none can look precise.
    (( utf8 )) || dot='.'
    PEGADA_TERM_SEGMENT="$bolt $dot"
    if (( ! quiet )); then
      printf '%*s\r' $(( ${COLUMNS:-80} - 1 )) ''
      print -r -- "$dim$bolt $dot$rst"
    fi
    return $ec
  fi

  local -i total=$(( __pegada_term_e - e0 ))
  # Above idle: what the machine used beyond its idle baseline for this long.
  local -i above=$(( total - __pegada_term_si * dur / 1000 ))
  (( above < 0 )) && above=0
  (( __pegada_term_ses_mj += total, __pegada_term_ses_above += above, __pegada_term_ses_n++ ))
  local approx= e_total e_above e_session
  (( dur < 4 * __pegada_term_sr )) && approx='~'
  __pegada_term_fmt_energy $total; e_total=$approx$REPLY
  __pegada_term_fmt_energy $above; e_above=$approx$REPLY
  __pegada_term_fmt_energy $__pegada_term_ses_mj; e_session=$REPLY
  PEGADA_TERM_SEGMENT="$bolt $e_total"

  if [[ ${PEGADA_TERM_HISTORY:-1} != 0 ]]; then
    __pegada_term_head $__pegada_term_cmd
    __pegada_term_log "${now%???}"$'\t'"$dur"$'\t'"$total"$'\t'"$above"$'\t'"$ec"$'\t'"$REPLY"
  fi
  if (( __pegada_term_osc )); then
    __pegada_term_uservars pegadaTermLast $e_total pegadaTermAbove $e_above pegadaTermSession $e_session
  fi
  (( quiet )) && return $ec

  # If the command's output did not end in a newline, this moves to a fresh
  # line; otherwise the spaces fit on the current one and \r returns to its start.
  printf '%*s\r' $(( ${COLUMNS:-80} - 1 )) ''
  if [[ $style == compact ]]; then
    print -r -- "$dim$bolt$rst $e_total"
    return $ec
  fi
  local e_time watts heat= spark=
  __pegada_term_fmt_time $dur; e_time=$REPLY
  local -i mw=$(( total * 1000 / dur ))
  if (( mw < 1000 )); then watts="$mw mW"; else watts="$(( mw / 1000 )).$(( mw % 1000 / 100 )) W"; fi
  if (( color )); then
    # Green below 100 J above idle, amber below 1 kJ, red from there.
    if (( above < 100000 )); then heat=$'\e[38;5;71m'
    elif (( above < 1000000 )); then heat=$'\e[38;5;214m'
    else heat=$'\e[38;5;203m'
    fi
  fi
  __pegada_term_spark $dur $color $utf8; spark=${REPLY:+ $REPLY  }
  print -r -- "$dim$bolt $e_total total $dot $rst$heat$e_above$rst$dim above idle $dot $e_time $dot $watts $rst$spark$dim$dot session $e_session$rst"
  return $ec
}

# `pegada-term on|off` toggles this shell; everything else goes to the binary,
# with this session's totals for `status`.
pegada-term() {
  case ${1-} in
    on) __pegada_term_on=1 ;;
    off) __pegada_term_on=0 __pegada_term_pending=0 PEGADA_TERM_SEGMENT= ;;
    *)
      PEGADA_TERM_SESSION_MJ=$__pegada_term_ses_mj \
        PEGADA_TERM_SESSION_ABOVE_MJ=$__pegada_term_ses_above \
        PEGADA_TERM_SESSION_CMDS=$__pegada_term_ses_n \
        $__pegada_term_bin "$@" ;;
  esac
}

# Register this shell: the sampler lives as long as some session file's pid
# does. Empty (even length) means "at the prompt".
{ : >| $__pegada_term_session } 2>/dev/null
add-zsh-hook preexec __pegada_term_preexec
add-zsh-hook precmd __pegada_term_precmd
